import { ArrowRight, Ban, Boxes, CheckCircle2, DatabaseZap, FileCheck2, Gauge, KeyRound, Layers, Lock, Radar, ScanSearch, ShieldAlert, Sparkles, Wrench } from "lucide-react";
import Link from "next/link";
import { IsolationDemo } from "@/ui/marketing/isolation-demo";
import { Reveal } from "@/ui/marketing/reveal";
import { SmoothScroll } from "@/ui/marketing/smooth-scroll";
import { Logo } from "@/ui/logo";
import { getSessionUser } from "@/infra/session";

export const dynamic = "force-dynamic";

const LAYERS = [
  { icon: Boxes, title: "The type system", body: "Every data call requires a TenantScope: a value that can only be created by verifying membership. Code that forgets the workspace doesn't compile." },
  { icon: DatabaseZap, title: "The query", body: "The workspace filter lives inside the same SQL statement as the vector search and the keyword search — never applied to results afterwards." },
  { icon: Lock, title: "The database", body: "Postgres row-level security applies to the app's role and fails closed: with no workspace set, every table returns zero rows." },
  { icon: Radar, title: "The proof", body: "Canary tests run on every build, and every answer has an inspector showing each chunk's workspace — so isolation is checked, not assumed." },
];

const STEPS = [
  ["Saved first", "Your question and a pending reply are committed before any model is called. A slow or failed provider can never lose them."],
  ["Condensed", "Follow-ups become standalone search queries, using only your conversation — never document text."],
  ["Hybrid retrieval", "Vector and keyword search run in one statement, scoped to the workspace, fused with reciprocal-rank fusion."],
  ["Fenced prompt", "Retrieved text is wrapped in delimiters carrying a per-request secret nonce, and labelled untrusted data."],
  ["Verified", "Every citation is checked against what was actually retrieved. Uncited answers are replaced with an honest “I don't know”."],
  ["Streamed", "Tokens stream as they arrive, with a retry that reuses the same question if anything fails."],
];

const TRUST = [
  { icon: FileCheck2, title: "Idempotent ingestion", body: "Re-uploading the same file never creates duplicate chunks; interrupted indexing resumes from a checkpoint." },
  { icon: Layers, title: "Provider failover", body: "Gemini models chain into Groq. Rate limits and outages fail over quietly instead of failing the user." },
  { icon: Gauge, title: "Observability", body: "Latency percentiles, token counts, retrieval hit rate and tool outcomes — per workspace." },
  { icon: KeyRound, title: "Secrets stay secret", body: "Webhook URLs are AES-256-GCM encrypted, bound to their workspace, and never shown after saving." },
  { icon: ScanSearch, title: "Inspectable", body: "See exactly which chunks each answer drew on, with scores from each retriever." },
  { icon: Sparkles, title: "Accessible by design", body: "Keyboard-first, screen-reader labelled, reduced-motion aware, with a table view behind every chart." },
];

const FAQ = [
  ["Is my data used to train models?", "Answers are generated by Google Gemini (with Groq as a fallback) on their free tiers. Free-tier terms may allow providers to use submitted content to improve their products, so do not upload sensitive material to a free deployment. Paid tiers change this; the providers are configurable."],
  ["What happens if a document tries to hijack the assistant?", "Document text is treated strictly as data. Even if a model were fully fooled, it can only call registered tools, arguments are validated against strict schemas, the workspace comes from your session, and any action proposed while suspicious text was in context waits for your approval."],
  ["What are the limits?", "Files up to 5 MB (PDF, DOCX, Markdown, text). Scanned PDFs without a text layer aren't supported. Sign-in uses email and password without email verification, because this build avoids paid mail services."],
  ["Can workspaces share a document?", "Yes — explicitly, per document, read-only, and revocable. The default is always sealed."],
];

export default async function Home() {
  const user = await getSessionUser();
  return (
    <div className="relative overflow-x-clip">
      <SmoothScroll />
      <header className="sticky top-0 z-30 border-b border-line/70 bg-canvas/80 backdrop-blur supports-[backdrop-filter]:bg-canvas/60">
        <div className="mx-auto flex h-16 max-w-6xl items-center gap-6 px-5">
          <Link href="/" aria-label="Lattice home"><Logo /></Link>
          <nav aria-label="Primary" className="ml-4 hidden items-center gap-6 text-sm text-ink-2 md:flex">
            <a className="hover:text-ink" href="#isolation">Isolation</a>
            <a className="hover:text-ink" href="#pipeline">How it works</a>
            <a className="hover:text-ink" href="#tools">Safe tools</a>
            <a className="hover:text-ink" href="#faq">FAQ</a>
          </nav>
          <div className="ml-auto flex items-center gap-2">
            {user ? (
              <Link href="/app" className="inline-flex h-10 items-center gap-2 rounded-md bg-brand px-4 text-sm font-medium text-brand-ink hover:brightness-110">Open app <ArrowRight className="size-4" /></Link>
            ) : (
              <>
                <Link href="/login" className="hidden h-10 items-center rounded-md px-4 text-sm font-medium text-ink-2 hover:text-ink sm:inline-flex">Sign in</Link>
                <Link href="/login" className="inline-flex h-10 items-center gap-2 rounded-md bg-brand px-4 text-sm font-medium text-brand-ink hover:brightness-110">Try the demo <ArrowRight className="size-4" /></Link>
              </>
            )}
          </div>
        </div>
      </header>

      <main id="main">
        <section className="relative">
          <div className="lattice-bg absolute inset-0 -z-10 opacity-60" aria-hidden />
          <div className="mx-auto grid max-w-6xl items-center gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1.05fr_1fr] lg:pb-28 lg:pt-24">
            <div>
              <Reveal eager>
                <p className="inline-flex items-center gap-2 rounded-full border border-line bg-panel px-3 py-1 text-[13px] text-ink-2"><span className="size-1.5 rounded-full bg-good" aria-hidden /> Multi-tenant RAG, built carefully</p>
              </Reveal>
              <Reveal eager delay={0.05}>
                <h1 className="mt-6 text-[2.6rem] font-semibold leading-[1.05] tracking-tight text-ink sm:text-6xl">Ask your documents.<br /><span className="text-brand">Keep every workspace sealed.</span></h1>
              </Reveal>
              <Reveal eager delay={0.1}>
                <p className="mt-6 max-w-xl text-lg text-ink-2">Lattice answers from the files you upload — with citations — and says “I don&apos;t know” when they don&apos;t contain the answer. Every workspace shares one vector store, yet none can ever see another&apos;s data.</p>
              </Reveal>
              <Reveal eager delay={0.15}>
                <div className="mt-8 flex flex-wrap items-center gap-3">
                  <Link href="/login" className="inline-flex h-12 items-center gap-2 rounded-md bg-brand px-6 text-base font-medium text-brand-ink shadow-1 hover:brightness-110">Try the live demo <ArrowRight className="size-4" /></Link>
                  <a href="#isolation" className="inline-flex h-12 items-center rounded-md border border-line-strong bg-panel px-6 text-base font-medium text-ink hover:bg-panel-2">See how isolation works</a>
                </div>
                <p className="mt-4 text-sm text-ink-3">No card. One-click demo account with two preloaded workspaces.</p>
              </Reveal>
            </div>
            <Reveal eager delay={0.12}><IsolationDemo /></Reveal>
          </div>
        </section>

        <section aria-label="At a glance" className="border-y border-line bg-panel">
          <dl className="mx-auto grid max-w-6xl grid-cols-2 gap-px bg-line md:grid-cols-4">
            {[["1", "shared vector table for every workspace"], ["4", "independent layers keeping tenants apart"], ["100%", "of tool calls validated and logged"], ["$0", "to run: free-tier stack, no card"]].map(([n, l]) => (
              <div key={l} className="bg-panel px-5 py-7 text-center">
                <dt className="text-3xl font-semibold tracking-tight text-ink tabular">{n}</dt>
                <dd className="mt-1 text-[13px] text-ink-2">{l}</dd>
              </div>
            ))}
          </dl>
        </section>

        <section id="isolation" className="mx-auto max-w-6xl scroll-mt-20 px-5 py-24">
          <Reveal>
            <h2 className="max-w-2xl text-3xl font-semibold tracking-tight text-ink sm:text-4xl">One store. Four walls.</h2>
            <p className="mt-4 max-w-2xl text-lg text-ink-2">A bug in any single layer is caught by the next one. Isolation is a security boundary here, not a UI convenience.</p>
          </Reveal>
          <div className="mt-12 grid gap-4 sm:grid-cols-2">
            {LAYERS.map((l, i) => (
              <Reveal key={l.title} delay={i * 0.06}>
                <div className="h-full rounded-xl border border-line bg-panel p-6">
                  <div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-brand-soft text-brand"><l.icon className="size-5" aria-hidden /></span><h3 className="text-lg font-semibold text-ink">{i + 1}. {l.title}</h3></div>
                  <p className="mt-3 text-ink-2">{l.body}</p>
                </div>
              </Reveal>
            ))}
          </div>
          <Reveal delay={0.1}>
            <figure className="mt-6 overflow-hidden rounded-xl border border-line bg-panel">
              <figcaption className="border-b border-line px-4 py-2.5 text-[12px] font-medium uppercase tracking-wide text-ink-3">The actual retrieval predicate (simplified)</figcaption>
              <pre className="overflow-x-auto p-4 font-mono text-[13px] leading-relaxed text-ink"><code>{`SELECT c.id
FROM chunks c
WHERE c.workspace_id = $active_workspace      -- inside the query, not after it
  AND c.embedding <=> $question_vector < …
ORDER BY (c.embedding <=> $question_vector)   -- exact search within the workspace

-- and independently, on every table:
CREATE POLICY chunks_select ON chunks TO lattice_app
  USING (workspace_id = app_workspace_id() AND app_workspace_authorized());`}</code></pre>
            </figure>
          </Reveal>
        </section>

        <section id="pipeline" className="scroll-mt-20 border-y border-line bg-panel">
          <div className="mx-auto max-w-6xl px-5 py-24">
            <Reveal>
              <h2 className="max-w-2xl text-3xl font-semibold tracking-tight text-ink sm:text-4xl">What happens when you ask a question</h2>
              <p className="mt-4 max-w-2xl text-lg text-ink-2">Six steps, each designed so that failure loses nothing and hallucination doesn&apos;t get through.</p>
            </Reveal>
            <ol className="mt-12 grid gap-x-10 gap-y-8 md:grid-cols-2">
              {STEPS.map(([t, b], i) => (
                <Reveal key={t} delay={(i % 2) * 0.06}>
                  <li className="flex gap-4">
                    <span className="grid size-9 shrink-0 place-items-center rounded-full border border-line-strong bg-panel-2 font-mono text-sm font-semibold text-ink" aria-hidden>{i + 1}</span>
                    <div><h3 className="font-semibold text-ink">{t}</h3><p className="mt-1 text-ink-2">{b}</p></div>
                  </li>
                </Reveal>
              ))}
            </ol>
          </div>
        </section>

        <section id="tools" className="mx-auto grid max-w-6xl scroll-mt-20 items-center gap-12 px-5 py-24 lg:grid-cols-2">
          <Reveal>
            <h2 className="text-3xl font-semibold tracking-tight text-ink sm:text-4xl">The model proposes. The app decides.</h2>
            <p className="mt-4 text-lg text-ink-2">The assistant can save tasks and post summaries — but every call is checked before anything runs.</p>
            <ul className="mt-6 space-y-3 text-ink-2">
              {["Only registered tools exist. An invented tool name is rejected and logged.", "Arguments are validated against strict schemas; a made-up workspace id is an error, not an instruction.", "If a retrieved document looked hostile, side-effect actions wait for your approval.", "Retries can never fire the same action twice."].map((t) => (
                <li key={t} className="flex gap-3"><CheckCircle2 className="mt-1 size-4 shrink-0 text-good" aria-hidden /><span>{t}</span></li>
              ))}
            </ul>
          </Reveal>
          <Reveal delay={0.08}>
            <div className="rounded-2xl border border-line bg-panel p-5 shadow-2" role="img" aria-label="Example tool log with one succeeded call, one blocked unknown tool, and one call awaiting approval">
              <p className="mb-3 flex items-center gap-2 text-sm font-semibold text-ink"><Wrench className="size-4 text-ink-3" aria-hidden /> Tool log</p>
              <ul className="space-y-2 text-sm">
                <li className="flex items-center gap-3 rounded-lg border border-line bg-panel-2 p-3"><span className="font-mono text-ink">save_task</span><span className="ml-auto inline-flex items-center gap-1 rounded-full bg-good-soft px-2 py-0.5 text-[11px] font-medium text-good"><CheckCircle2 className="size-3" aria-hidden /> Succeeded</span></li>
                <li className="flex items-center gap-3 rounded-lg border border-line bg-panel-2 p-3"><span className="font-mono text-ink">delete_everything</span><span className="ml-auto inline-flex items-center gap-1 rounded-full bg-bad-soft px-2 py-0.5 text-[11px] font-medium text-bad"><Ban className="size-3" aria-hidden /> Blocked: no such tool</span></li>
                <li className="rounded-lg border border-warn/40 bg-warn-soft p-3"><div className="flex items-center gap-3"><span className="font-mono text-ink">send_summary</span><span className="ml-auto inline-flex items-center gap-1 rounded-full bg-warn-soft px-2 py-0.5 text-[11px] font-medium text-warn"><ShieldAlert className="size-3" aria-hidden /> Needs your approval</span></div><p className="mt-1.5 text-[13px] text-ink-2">A retrieved document contained instructions aimed at the assistant, so this was not run.</p></li>
              </ul>
            </div>
          </Reveal>
        </section>

        <section className="border-y border-line bg-panel">
          <div className="mx-auto max-w-6xl px-5 py-24">
            <Reveal><h2 className="max-w-2xl text-3xl font-semibold tracking-tight text-ink sm:text-4xl">Built to run unattended</h2></Reveal>
            <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {TRUST.map((t, i) => (
                <Reveal key={t.title} delay={(i % 3) * 0.05}>
                  <div className="h-full rounded-xl border border-line bg-canvas p-5"><t.icon className="size-5 text-brand" aria-hidden /><h3 className="mt-3 font-semibold text-ink">{t.title}</h3><p className="mt-1.5 text-sm text-ink-2">{t.body}</p></div>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        <section id="faq" className="mx-auto max-w-3xl scroll-mt-20 px-5 py-24">
          <Reveal><h2 className="text-3xl font-semibold tracking-tight text-ink sm:text-4xl">Straight answers</h2></Reveal>
          <div className="mt-8 divide-y divide-line rounded-xl border border-line bg-panel">
            {FAQ.map(([q, a]) => (
              <details key={q} className="group p-5">
                <summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-medium text-ink [&::-webkit-details-marker]:hidden">{q}<span className="text-ink-3 transition-transform group-open:rotate-45" aria-hidden>+</span></summary>
                <p className="mt-3 text-ink-2">{a}</p>
              </details>
            ))}
          </div>
        </section>

        <section className="mx-auto max-w-6xl px-5 pb-24">
          <Reveal>
            <div className="relative overflow-hidden rounded-2xl border border-line bg-panel p-10 text-center sm:p-16">
              <div className="lattice-bg absolute inset-0 opacity-50" aria-hidden />
              <div className="relative">
                <h2 className="mx-auto max-w-xl text-3xl font-semibold tracking-tight text-ink sm:text-4xl">Try to break the isolation.</h2>
                <p className="mx-auto mt-4 max-w-lg text-ink-2">Open the demo, ask Acme Corp for its vault code, then switch to Beta Labs and ask again.</p>
                <Link href="/login" className="mt-8 inline-flex h-12 items-center gap-2 rounded-md bg-brand px-6 text-base font-medium text-brand-ink hover:brightness-110">Open the demo <ArrowRight className="size-4" /></Link>
              </div>
            </div>
          </Reveal>
        </section>
      </main>

      <footer className="border-t border-line">
        <div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-5 py-8 text-sm text-ink-3">
          <Logo className="opacity-80" />
          <p>Next.js · Postgres + pgvector · Gemini &amp; Groq · Built on a free-tier stack.</p>
        </div>
      </footer>
    </div>
  );
}
